### PR TITLE
Migrate to Guider

### PR DESCRIPTION
**Pull request by mrjvs**
## Why move to Guider?
1. Docus is deprecated, is no longer being maintained
2. More flexible
3. Guider is better (and made by me <3, an ex-contributor)

## Changes
- Moved to Guider instead of Docus
- Migrated files to MDX files
- Fixed an outdated link (anchor was wrong)
- Fixed broken codeblock in selfhost.md

## Feature regressions
- target blank links have been removed, not supported
- copy buttons on random pieces of text have been removed, not supported
- light theme is gone 🦀 
- Category icons have been removed, not supported
- Title no longer shows subdirectory, only shows `| movie-web` as a suffix

### CODE REVIEW

**Comment by qtchaos** [comment]
YES!!!!!!!!!!!!!

**Comment by mrjvs** [comment]
@qtchaos should be ready for review now. Since it's a big migration, I've made every commit a seperate isolated change so it's easier to click through.

**Review by qtchaos — CHANGES_REQUESTED** [review]
When clicking on links that are supposed to redirect to another `mdx` file, they don't include the base path `docs/` and for some reason seem to flip the slash (`/client\proxy`).

**Comment by mrjvs** [comment]
> When clicking on links that are supposed to redirect to another `mdx` file, they don't include the base path `docs/` and for some reason seem to flip the slash (`/client\proxy`). This results in a 404 error since the path doesn't make any sense.

This was fixed in the newest version of guider, just updated the PR. (Was a windows only issue)

**Review by qtchaos — APPROVED** [review]

**Pull request merged**
